"""
NVD CVE Dashboard — Home / Overview
Entry point for `streamlit run app.py`. The four analysis pages live in
pages/ and appear automatically in the sidebar.
"""
import pandas as pd
import streamlit as st

from utils.data_loader import (
    EXPECTED_FILES,
    any_data_present,
    data_path,
    load_csv,
    model_path,
    status_table,
)
from utils.style import SEV_ORDER, kpi_number

st.set_page_config(page_title="NVD CVE Dashboard", page_icon="🛡️", layout="wide")

st.title("🛡️ NVD CVE Dashboard")
st.caption(
    "Data Mining and Analysis of Cybersecurity Vulnerabilities Using NVD CVE Data — "
    "IS-212 Data and Knowledge Mining project"
)

st.markdown(
    """
This app is a viewer over the project notebook's saved results — it doesn't
re-run TF-IDF, POS-lemmatization, UMAP or association-rule mining live (that
would take minutes per interaction on 100,000 records). Instead it reads the
CSVs the notebook already writes with `.to_csv(...)`, so every page loads
instantly.

**Use the sidebar to open:**
- **EDA Dashboard** — CVE volume, severity, CVSS scores, attack characteristics,
  top vendors/products/CWEs, KEV trends, correlations
- **Clustering Explorer** — browse text-only vs. joint clusters, their top
  terms, and how they line up with severity/CWE/known-exploited status
- **Association Rules** — filter and sort the mined support/confidence/lift
  rules
- **Severity Predictor** — type a CVE-style description and get a live
  severity prediction from the trained TF-IDF + Logistic Regression model
"""
)

st.divider()

if not any_data_present():
    st.warning(
        "No data files found yet. Run the project notebook end-to-end, then copy its "
        f"`.to_csv(...)` outputs into `{data_path('desc_clusters').parent}` — see the "
        "setup checklist below for exact filenames."
    )
else:
    df = None
    for key in ("desc_clusters", "joint_clusters"):
        if data_path(key).exists():
            df = load_csv(key)
            break

    if df is not None:
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Total CVEs", kpi_number(len(df)))
        if "published_year" in df.columns:
            col2.metric(
                "Year range",
                f"{int(df['published_year'].min())}–{int(df['published_year'].max())}",
            )
        if "base_severity" in df.columns:
            high_crit = df["base_severity"].isin(["HIGH", "CRITICAL"]).mean() * 100
            col3.metric("High + Critical", f"{high_crit:.1f}%")
        if "is_known_exploited" in df.columns:
            col4.metric("Known-exploited", kpi_number(int(df["is_known_exploited"].sum())))

        if "base_severity" in df.columns:
            st.caption("Severity mix (from the loaded dataset)")
            counts = df["base_severity"].value_counts().reindex(SEV_ORDER).fillna(0)
            st.bar_chart(counts)

st.divider()
st.subheader("Setup checklist")
st.caption(
    "Every row below is a file this app looks for in `data/` (or `models/` for the "
    "trained predictor). Pages that need a missing file will tell you exactly which one."
)
status = status_table()
status_display = status["found"].map(lambda ok: "✅" if ok else "⬜")
st.dataframe(
    pd.DataFrame({"file": status["file"], "status": status_display}),
    hide_index=True,
    use_container_width=True,
)

if not model_path().exists():
    st.info(
        "The Severity Predictor page needs a trained model that isn't generated by the "
        "notebook itself. Run `python train_severity_model.py` from this folder once "
        "you have `nvd_cve_with_description_clusters.csv` in `data/`."
    )
